### ISSUE TITLE
composer

### ISSUE THREAD

**Issue by ikwattro** [JoranBeaufort/Neo4jUserBundle#1]
Please add a composer config so we can require it in our deps

**Comment by JoranBeaufort** [comment]
Working on it. (Truth be told, have never created a composer repo before, so might take a while )

**Comment by ikwattro** [comment]
No worries, let me know if you need help

**Comment by JoranBeaufort** [comment]
Thanks. Gotta learn sometime :) Thanks for the requirements hint. Also quite new to github btw ^^

**Comment by JoranBeaufort** [comment]
Ok, updated the readme and alot of things in the Bundle. Now the connection information is provided in the config.yml. I hope this works on your install? Seems to work on mine.

**Comment by ikwattro** [comment]
Just did a quick check, in general I find you override a LOT of the FOSUserBundle, it is quite some time I didn't used it so I might be wrong, but I remember at the time that you could override default implementation of the FOS one with compiler passes and just add the neo4j specific logic needed.

More neo4j-ogm related, regarding the `isEnabled()`, here you use a boolean property : 

https://github.com/JoranBeaufort/Neo4jUserBundle/blob/master/src/Entity/User.php#L145

Which is fine. Just my personal opinion (and also my experience with building neo4j backed applications on a daily basis) I generally tend to use dedicated labels.

You can use them with the `Label` annotation which will set / unset the label depending if the value of the property is true / false. A common label is `RegisteredUser`.

Example here : https://github.com/graphaware/neo4j-php-ogm/blob/master/tests/Integration/Model/User.php#L45

**Comment by JoranBeaufort** [comment]
Thanks for the comments! Yes, I basically took the FOSUserBundle and overwrote everything. Would you suggest to trash this git and create a new one with overriding the FOS defaults? I can only remember, that I didnt get very far last time I tried, but I should have a more solid understanding now. What would you suggest?

**Comment by ikwattro** [comment]
I would suggest to have something you are confident with. If you feel confident by the code you have, go for it. It doesn't embrace reusability but a good point is that you'll discover new parts of Symfony itself

**Comment by JoranBeaufort** [comment]
Thanks for your advice and time, I appreciate it! I will have a look into the FOSUserBundle but will probably stick with my bundle for the moment. Best regards!
